name: CI/CD for Go

on:
  push:
    branches: [ "main" ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 📦 Checkout source code
      uses: actions/checkout@v4

    - name: 🚀 Deploy to VPS
      uses: appleboy/ssh-action@v1.2.2
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: 22
        script: |
          echo "🔄 Pulling latest code..."
          cd /home/${{secrets.VPS_USER}}/vidhub/vidbox-api
          git reset --hard
          git pull origin main
          echo "🐳 Restarting Docker containers..."
          docker compose build             # build local image từ Dockerfile
          docker compose up -d --remove-orphans
          echo "🧹 Cleaning up Docker cache and old images..."
          docker builder prune -af
          docker image prune -f
          echo "✅ Deploy completed!"
    - name: 📢 Notify to Telegram
      if: always()
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        JOB_STATUS: ${{ job.status }}
      run: |
        if [ "$JOB_STATUS" = "success" ]; then
          STATUS_ICON="✅"
          STATUS_TEXT="*Deploy thành công!*"
        elif [ "$JOB_STATUS" = "cancelled" ]; then
          STATUS_ICON="⚠️"
          STATUS_TEXT="*Deploy bị huỷ!*"
        else
          STATUS_ICON="❌"
          STATUS_TEXT="*Deploy thất bại!*"
        fi

        curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" \
          -d chat_id="${TELEGRAM_CHAT_ID}" \
          -d parse_mode=Markdown \
          -d text="${STATUS_ICON} ${STATUS_TEXT} \nRepo: \`${{ github.repository }}\`\nBranch: \`${{ github.ref_name }}\`\nCommit: [${{ github.sha }}](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})"
        
